global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: /api/metrics
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/metrics_password.txt
    static_configs:
      - targets: ["backend:3000"]
